AWSTemplateFormatVersion: 2010-09-09
Description: EMR SecurityGroup Defns

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: target VPC
    Default: vpc-05b28a46c5c9c6ed7

Resources:
  MasterSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: gordo-group
      GroupDescription: Hughs EMR security group - blame him
      VpcId: !Ref VPC

  MasterIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref MasterSecurityGroup
      CidrIp: 0.0.0.0/0
      FromPort: -1
      ToPort: -1
      IpProtocol: icmp
#      SourceSecurityGroupId: !Ref MasterSecurityGroup

  MasterEgress:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref MasterSecurityGroup
      CidrIp: 0.0.0.0/0
      FromPort: 0
      ToPort: 65535
      IpProtocol: -1
#      DestinationSecurityGroupId: !Ref MasterSecurityGroup

Outputs:
  MainSecurityGroup:
    Description: main securityGroup
    Value: !Ref MasterSecurityGroup
    Export:
      Name: "master-sg"
